saml.identity_provider.*:
  type: config_entity
  label: Identity Provider
  mapping:
    id:
      type: string
      label: ID
    label:
      type: string
      label: Name
    encrypted_response:
      type: boolean
      label: Wants encrypted response
    encryption_algorithm:
      type: string
      label: Encryption algorithm
    encryption_certificate:
      type: string
      label: Encryption certificate
    encryption_key:
      type: string
      label: Encryption key
    signed_response:
      type: string
      label: Wants signed response
    signature_certificate:
      type: string
      label: Signature certificate
    issuer:
      type: string
      label: Issuer
    issuer_format:
      type: string
      label: Issuer format
    mail_attribute:
      type: string
      label: Mail attribute
