saml.service_provider.*:
  type: config_entity
  label: Service Provider
  mapping:
    id:
      type: string
      label: ID
    label:
      type: string
      label: Name
    encrypted_response:
      type: boolean
      label: Encrypted response
    encryption_response_algorithm:
      type: string
      label: Encryption algorithm
    encryption_response_certificate:
      type: string
      label: Encryption certificate
    encryption_response_key:
      type: string
      label: Encryption key
    signed_response:
      type: boolean
      label: Signed response
    signature_response_algorithm:
      type: string
      label: Signature response algorithm
    signature_response_certificate:
      type: string
      label: Signature response certificate
    signature_response_key:
      type: string
      label: Signature response key
    signed_request:
      type: boolean
      label: Signed request
    signature_request_algorithm:
      type: string
      label: Signature request algorithm
    signature_request_certificate:
      type: string
      label: Signature request certificate
    signature_request_key:
      type: string
      label: Signature request key
    issuer_format:
      type: string
      label: Issuer format
    issuer:
      type: string
      label: Issuer
    name_id_format:
      type: string
      label: Name ID format
    email_attribute:
      type: string
      label: Email attribute
    sso_url:
      type: string
      label: Sign Sign On URL
